=== cairo-caplan/uap/cfg/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Virtual Repository IP list (array of entries)",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Name", "Category"],
    "properties": {
      "Name": { "type": "string", "minLength": 1 },
      "Category": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "URL": { "type": "string", "format": "uri" },
      "IP_CARD_URL":{"type":"string","format":"ip_card_json"},
      "IP_CARD_PDF_URL":{"type":"string","format":"ip_card_pdf"},
      "Project": { "type": "string" },
      "WI": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Partners": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Status": { "type": "string" },
      "Description": { "type": "string" },
      "License": {
         "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Comment": { "type": "string" }
    },
    "additionalProperties": true
  }
}

=== cairo-caplan/uap/ips/ISOLDE.json
[
  {
    "Project": "ISOLDE",
    "Name": "NOEL-V processor extensions",
    "URL": "",
    "License": [
      "GPL-2.0-or-later",
      "Proprietary"
    ],
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.01"
    ],
    "Partners": "GSL",
    "Comment": "GPL. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Core",
      "Extension"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "CVA6 processor extensions",
    "URL": "",
    "License": "SHL-2.1",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.02"
    ],
    "Partners": "TDIS",
    "Comment": "Solderpad. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Core",
      "Extension"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "CV32E40X processor extensions",
    "URL": "",
    "License": "MIT",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.03"
    ],
    "Partners": "HM",
    "Comment": "MIT. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Core",
      "Extension"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Testing Design Parameters for CVA6",
    "URL": "",
    "License": "Others",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.04"
    ],
    "Partners": "UZL",
    "Comment": "Open Source. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Core",
      "Tool"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Analysis Framework",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.05"
    ],
    "Partners": "IFX",
    "Comment": "Proprietary. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Tool"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Context-Aware Bus",
    "URL": "",
    "License": "SHL-2.1",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.01"
    ],
    "Partners": "TRT",
    "Comment": "Solderpad. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Wormhole NoC",
    "URL": "https://gitlab.com/selene-riscv-platform/euros2pronoc/-/tree/AXI-MM-Network-Interface?ref_type=heads",
    "License": "MIT",
    "Status": "Completed, tested",
    "Description": "Tile-oriented SoC design, where components located at different tiles exchange messages in a unified manner. IPs will interface to the NoC by means of a Network Interface (NI) which complies with AXI protocol. The NoC router supports 2D mesh topologies.",
    "WI": [
      "ID 2.2.02"
    ],
    "Partners": "UPV",
    "Comment": "MIT. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "NoC"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "AXI Sniffer",
    "URL": "https://gitlab.com/selene-riscv-platform/selene-hardware/-/tree/master/interconnect/libnoc/mem_monitor",
    "License": "MIT",
    "Status": "Completed, verified",
    "Description": "Monitors the network activity in AXI interconnects. Tracks the timing contention between the different traffic sources on an AXI network for each given destination.",
    "WI": [
      "ID 2.2.03"
    ],
    "Partners": "UPV",
    "Comment": "MIT. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "On-Chip Debug System",
      "Tool",
      "Visualisation and Debugging"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "AHB Crossbar",
    "URL": "",
    "License": "Others",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.04"
    ],
    "Partners": "IFX",
    "Comment": "TBD. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "AHB/APB Interrupt Controller",
    "URL": "",
    "License": "Others",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.05"
    ],
    "Partners": "IFX",
    "Comment": "TBD. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Peripheral"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "AHB/APB Timer",
    "URL": "",
    "License": "Others",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.06"
    ],
    "Partners": "IFX",
    "Comment": "TBD. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Peripheral"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "GRLIB IP library",
    "URL": "https://www.gaisler.com/getgrlib",
    "License": [
      "GPL-2.0-or-later",
      "Proprietary"
    ],
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.07"
    ],
    "Partners": "GSL",
    "Comment": "GPL. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Core",
      "Peripheral",
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Hypervisor virtualization support to low-cost HW IPs",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.08"
    ],
    "Partners": "FENTISS",
    "Comment": "Proprietary. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Extension"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Context-Aware CORE Extensions",
    "URL": "",
    "License": "SHL-2.1",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.01"
    ],
    "Partners": "TRT",
    "Comment": "Solderpad. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Extension"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Memory bank interface",
    "URL": "https://bitbucket.org/fnpub/isolde/",
    "License": [
      "SHL-0.51"
    ],
    "Status": "Completed, verified",
    "Description": "Interface protocol for acessing internal memory banks of the AI/ML accelerator",
    "WI": [
      "ID 2.3.02"
    ],
    "Partners": "FotoNation",
    "Comment": "Open Source. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Peripheral",
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Extension interface for NOEL-V",
    "URL": "",
    "License": [
      "GPL-2.0-or-later",
      "Proprietary"
    ],
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.03"
    ],
    "Partners": "GSL",
    "Comment": "GPL. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Extension",
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Extension interface for CVA6",
    "URL": "",
    "License": "SHL-2.1",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.04"
    ],
    "Partners": "TDIS",
    "Comment": "Solderpad. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Extension",
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "Interface between CVA6 and Vector accelerator",
    "URL": "https://github.com/pulp-platform/ara/tree/f06204b",
    "License": "SHL-2.1",
    "Status": "Prototype. To be updated with the final release of CV-X-IF in CVA6",
    "Description": "Prototype of CV-X-IF between CVA6 and RVV 1.0 vector processor, used for evaluation",
    "WI": [
      "ID 2.3.05"
    ],
    "Partners": "ETHZ",
    "Comment": "Solderpad. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Extension",
      "Interface"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "XNG NOEL-V BSP update to RISC-V new specifications",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.01"
    ],
    "Partners": "FENTISS",
    "Comment": "Proprietary. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Software"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "CVA6 multicore experiments and analysis",
    "URL": "",
    "License": "Others",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.02"
    ],
    "Partners": "SYSGO",
    "Comment": "TBD. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Core",
      "Core Generator"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "SW Abstraction Layer for RISC-V Processors",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.03"
    ],
    "Partners": "IFX",
    "Comment": "Proprietary. ISOLDE Category 'Cores, interfaces, peripherals & NoCs'",
    "Category": [
      "Software"
    ],
    "IP_CARD_URL": "",
    "IP_CARD_PDF_URL": ""
  },
  {
    "Project": "ISOLDE",
    "Name": "NOEL-V software tools",
    "URL": "",
    "License": [
      "GPL-2.0-or-later",
      "Proprietary"
    ],
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.04"
    ],
